### ISSUE TITLE
missing dependency - library(http/json)

### ISSUE THREAD

**Issue by alkan** [rla/node-swipl-stdio#1]
It is not in swipl's add-ons list.  How can we get it?

**Comment by rla** [comment]
The module `library(http/json)` is part of SWI-Prolog and not this package. You will likely need to re-install your SWI-Prolog. Installation (build) instructions for Linux or BSD can be found from here:
<http://www.swi-prolog.org/build/unix.html>. If you have issues when following the build instructions, file them directly to <https://github.com/SWI-Prolog/issues>. Windows, OSX and Linux binary versions should have the missing module bundled in already.

**Comment by rla** [comment]
Closing as no feedback so far.
